name: Build and Release

on:
  push:
    tags:
    - 'v*' 

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/Chirp.CLI
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/Chirp.CLI
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/Chirp.CLI
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/SimpleDB
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/SimpleDB
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/SimpleDB

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
            src/Chirp.CLI
            README.md
