name: Build and Release

on:
  push:
    tags:
    - 'v*' 

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
      # Same code as build-and-test for CHirp.CLI, purely to be absolutely sure we don't publish something that fails our tests
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/Chirp.CLI
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/Chirp.CLI
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/Chirp.CLI

      # Inspired by: https://patriksvensson.se/posts/2020/03/creating-release-artifacts-with-github-actions
    - name: Build
      shell: bash
      run: |
        tag=$(git describe --tags --abbrev=0)
        windows_release_name="win-$tag"
        mac_release_name="mac-$tag"
        linux_release_name="linux-$tag"
        
        # Windows build
        dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime win-x64 -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true -o "$windows_release_name"        
        win_executable_path="$windows_release_name/Chirp.CLI.exe"
        mv "$win_executable_path" "./$windows_release_name.exe"

        # Mac build
        dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime osx-x64 -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true -o "$mac_release_name"

        # Linux build
        dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime linux-x64 -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true -o "$linux_release_name"        
        
        7z a -tzip "${windows_release_name}.zip" "./${windows_release_name}.exe"      
        7z a -tzip "${mac_release_name}.zip" "./${mac_release_name}/Chirp.CLI"
        7z a -tzip "${linux_release_name}.zip" "./${linux_release_name}/Chirp.CLI"
        
        rm "./$windows_release_name.exe"
        
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          "win-*.zip"
          "mac-*.zip"
          "linux-*.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
