name: .NET Build and Test

on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/Chirp.Razor/Chirp.Web
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/Chirp.Razor/Chirp.Web
    - name: Test
      env: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet test --verbosity normal
      working-directory: test/Chirp.Razor.Tests
