name: .NET Build and Test

on:
  push:
    branches: [ main, WorkflowPlaywright ]
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/Chirp.Razor/Chirp.Web
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/Chirp.Razor/Chirp.Web

    - name: Test
      run: |
        export authentication_github_clientId="${{ secrets.GITHUBCLIENTID }}"
        export authentication_github_clientSecret="${{ secrets.GITHUBCLIENTSECRET }}"
        dotnet test test/Chirp.Razor.Tests --verbosity normal 
        
  PlayWrightTest: # Inspiration from https://playwright.dev/docs/ci-intro
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build
      working-directory: test/Chirp.Razor.Tests/PlaywrightTests

    - name: Install playwright browser
      run: pwsh test/Chirp.Razor.Tests/PlaywrightTests/bin/Debug/net8.0/playwright.ps1 install --with-deps

    - name: Run Playwright tests
      run: |
        export authentication_github_clientId="${{ secrets.GITHUBCLIENTID }}"
        export authentication_github_clientSecret="${{ secrets.GITHUBCLIENTSECRET }}"
        dotnet test test/Chirp.Razor.Tests/PlaywrightTests/ --verbosity normal
      
    
