name: Build and deploy ASP.Net Core app to Azure Web App - bdsagroup021chirprazor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build with dotnet
        run: dotnet build src/Chirp.Razor/Chirp.Web --configuration Release
      - name: Test
        run: |
          export authentication_github_clientId="${{ secrets.GITHUBCLIENTID }}"
          export authentication_github_clientSecret="${{ secrets.GITHUBCLIENTSECRET }}"
          dotnet test test/Chirp.Razor.Tests --verbosity normal
      - name: dotnet publish
        run: dotnet publish src/Chirp.Razor/Chirp.Web -c Release -o ./myapp
      - name: Verify publish output
        run: ls -la ./myapp
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp
      - name: Apply migrations
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          dotnet ef database update
        env:
          ASPNETCORE_ENVIRONMENT: Development

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: ./downloaded-artifact

    - name: List downloaded files
      run: ls -la ./downloaded-artifact

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FB60A92C9E0D4FC5A6F7CA7DA02FC357 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_79C508FB889C48F38C74CAD77BA32B75 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5C9A4EBD099B47878A5454FDE09377B0 }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'bdsagroup021chirprazor'
        slot-name: 'Production'
        package: ./downloaded-artifact
        runtime-stack: 'DOTNETCORE|8.0'
      env:
        GitHub__ClientId: ${{ secrets.GITHUBCLIENTID }}
        GitHub__ClientSecret: ${{ secrets.GITHUBCLIENTSECRET }}
