name: Build and Release

on:
  push:
#    tags:
#   - 'v*' 

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
      # Same code as build-and-test, purely to be absolutely sure we don't publish something that fails our tests
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/Chirp.CLI
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/Chirp.CLI
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/Chirp.CLI
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/SimpleDB
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/SimpleDB
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/SimpleDB
      # Build our artefacts
      # Inspired by: https://patriksvensson.se/posts/2020/03/creating-release-artifacts-with-github-actions
    - name: Get tag
      id: get-tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Windows prefix
      run: |
        tag=${{ env.TAG_NAME }}
        release_name="win-$tag"
    
    - name: Build
      shell: bash
      run: |
        dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime win-x64 -c Release -o "$release_name"
        7z a -tzip "${release_name}.zip" "./${release_name}/*"
        rm -r "$release_name"
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: "src/Chirp.CLI*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
